[project]
name = "fictive"
version = "0.1.0"
description = "An interactive fiction tool based on state machines"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mypy>=1.17.1",
    "ruamel-yaml>=0.18.15",
    "textual>=6.0.0",
    "textual-dev>=1.7.0",
]
